apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: IIPLpjHoinXf0jfxzEndoyCQZMdBUdHdhFt4ReMTLHsQTLJzBVVHMwldsKJD5NWKfGGjKp6OU6GJyfSN5iFeaRBHjjS8cfptj
spec:
  lifecycle: production
  owner: my-team
  type: service
